### ISSUE TITLE
BAFTA game name needs changing.

### ISSUE THREAD

**Issue by JDWOfficial** [TAAGameProjects/Mass-Effect-Fan-Project#2]
The current Mass Effect fan game is titled "TAABAFTAPROJECT" however, this is not the case. The ME fan game is NOT the BAFTA game. The BAFTA game needs to be completly original, and this is not. The BAFTA game is automatically copyrighted once entered as a project, and this would be seen as Copyright infringement. The BAFTA project is a separate entity, and the name needs to be changed to avoid confusion.  Thanks.

**Comment by ZanderBrown** [comment]
Any thoughts?

**Comment by JDWOfficial** [comment]
Maybe it could change to "Mass effect Fan game projects"?

**Comment by ZanderBrown** [comment]
Was meaning for the actual entry

**Comment by berserkergaming** [comment]
This issue has been resolved as seen by the title.
