### ISSUE TITLE
JSON Issues

### ISSUE THREAD

**Issue by JDWOfficial** [TAAGameProjects/Mass-Effect-Fan-Project#5]
Need to change from JSON to normal PY. JSON is having a fit when trying to work with school computers.
![image](https://cloud.githubusercontent.com/assets/25201663/22198919/908b0592-e150-11e6-9fa6-d8cd7f7d21b0.png)

Preferably Zander can fix this, as Zander knows more about JSON than any of us

THANKS!

**Comment by ZanderBrown** [comment]
Have you downloaded strings.json to the same folder as game.py?

**Comment by berserkergaming** [comment]
The issue has been resolved in C7 on Monday the 23rd
